import db from './schema';

export const seedExercises = () => {
  const count = db.getFirstSync('SELECT COUNT(*) as c FROM exercises').c;
  if (count > 0) return;

  const exercises = [

    // ─── CHEST (Push) ───────────────────────────────────────────
    { id: 'barbell-bench-press', name: 'Barbell Bench Press', category: 'Push',
      muscle_group: 'Chest', equipment: 'Barbell',
      instructions: 'Lie flat on bench. Grip bar slightly wider than shoulder width. Lower to chest, press up explosively.' },
    { id: 'incline-bench-press', name: 'Incline Bench Press', category: 'Push',
      muscle_group: 'Chest', equipment: 'Barbell',
      instructions: 'Set bench to 30-45 degrees. Grip bar wider than shoulders. Lower to upper chest, press up.' },
    { id: 'decline-bench-press', name: 'Decline Bench Press', category: 'Push',
      muscle_group: 'Chest', equipment: 'Barbell',
      instructions: 'Set bench to -15 degrees. Lower bar to lower chest. Targets lower pecs.' },
    { id: 'db-bench-press', name: 'Dumbbell Bench Press', category: 'Push',
      muscle_group: 'Chest', equipment: 'Dumbbell',
      instructions: 'Hold dumbbells at chest level. Press up and slightly inward. Greater range of motion than barbell.' },
    { id: 'incline-db-press', name: 'Incline DB Press', category: 'Push',
      muscle_group: 'Chest', equipment: 'Dumbbell',
      instructions: 'Set bench to 30-45 degrees. Press dumbbells up from upper chest.' },
    { id: 'db-fly', name: 'Dumbbell Fly', category: 'Push',
      muscle_group: 'Chest', equipment: 'Dumbbell',
      instructions: 'Lie on bench. Arms wide with slight elbow bend. Bring dumbbells together over chest in arc motion.' },
    { id: 'cable-fly', name: 'Cable Chest Fly', category: 'Push',
      muscle_group: 'Chest', equipment: 'Cable',
      instructions: 'Set cables at shoulder height. Step forward, bring handles together in front of chest.' },
    { id: 'low-cable-fly', name: 'Low Cable Fly', category: 'Push',
      muscle_group: 'Chest', equipment: 'Cable',
      instructions: 'Set cables at low position. Bring handles up and together to target upper chest.' },
    { id: 'chest-dip', name: 'Chest Dip', category: 'Push',
      muscle_group: 'Chest', equipment: 'Bodyweight',
      instructions: 'Lean forward on dip bars. Lower until shoulders below elbows. Press back up.' },
    { id: 'push-up', name: 'Push Up', category: 'Push',
      muscle_group: 'Chest', equipment: 'Bodyweight',
      instructions: 'Hands slightly wider than shoulders. Lower chest to floor. Keep core tight throughout.' },
    { id: 'wide-push-up', name: 'Wide Push Up', category: 'Push',
      muscle_group: 'Chest', equipment: 'Bodyweight',
      instructions: 'Hands much wider than shoulder width. Emphasizes chest over triceps.' },
    { id: 'pec-deck', name: 'Pec Deck', category: 'Push',
      muscle_group: 'Chest', equipment: 'Machine',
      instructions: 'Sit at machine. Bring arms together in front of chest. Squeeze at peak contraction.' },

    // ─── SHOULDERS (Push) ────────────────────────────────────────
    { id: 'overhead-press', name: 'Overhead Press', category: 'Push',
      muscle_group: 'Shoulders', equipment: 'Barbell',
      instructions: 'Stand with bar at shoulder height. Press overhead until arms locked. Lower under control.' },
    { id: 'seated-db-press', name: 'Seated DB Shoulder Press', category: 'Push',
      muscle_group: 'Shoulders', equipment: 'Dumbbell',
      instructions: 'Sit upright. Press dumbbells from ear level to overhead. Keep core braced.' },
    { id: 'arnold-press', name: 'Arnold Press', category: 'Push',
      muscle_group: 'Shoulders', equipment: 'Dumbbell',
      instructions: 'Start with palms facing you. Rotate outward as you press overhead. Reverse on descent.' },
    { id: 'lateral-raise', name: 'Lateral Raise', category: 'Push',
      muscle_group: 'Shoulders', equipment: 'Dumbbell',
      instructions: 'Slight elbow bend. Raise arms out to sides to shoulder height. Control descent.' },
    { id: 'cable-lateral-raise', name: 'Cable Lateral Raise', category: 'Push',
      muscle_group: 'Shoulders', equipment: 'Cable',
      instructions: 'Stand beside cable. Pull handle out to side. Cable keeps tension throughout range.' },
    { id: 'front-raise', name: 'Front Raise', category: 'Push',
      muscle_group: 'Shoulders', equipment: 'Dumbbell',
      instructions: 'Hold dumbbells in front of thighs. Raise forward to shoulder height. Alternate arms.' },
    { id: 'reverse-fly', name: 'Reverse Fly', category: 'Push',
      muscle_group: 'Shoulders', equipment: 'Dumbbell',
      instructions: 'Hinge forward at hips. Raise arms out to sides. Targets rear delts.' },
    { id: 'face-pull', name: 'Face Pull', category: 'Pull',
      muscle_group: 'Shoulders', equipment: 'Cable',
      instructions: 'Set cable at face height with rope. Pull to face, flare elbows out. Targets rear delts and rotator cuff.' },
    { id: 'upright-row', name: 'Upright Row', category: 'Push',
      muscle_group: 'Shoulders', equipment: 'Barbell',
      instructions: 'Grip bar narrow. Pull up along body to chin level. Elbows lead the movement.' },
    { id: 'machine-shoulder-press', name: 'Machine Shoulder Press', category: 'Push',
      muscle_group: 'Shoulders', equipment: 'Machine',
      instructions: 'Set seat height so handles are at shoulder level. Press overhead. Safe for heavy loads.' },

    // ─── TRICEPS (Push) ──────────────────────────────────────────
    { id: 'tricep-pushdown', name: 'Tricep Pushdown', category: 'Push',
      muscle_group: 'Triceps', equipment: 'Cable',
      instructions: 'Use rope or bar attachment at high cable. Keep elbows pinned to sides. Extend arms fully.' },
    { id: 'overhead-tricep-ext', name: 'Overhead Tricep Extension', category: 'Push',
      muscle_group: 'Triceps', equipment: 'Dumbbell',
      instructions: 'Hold dumbbell overhead with both hands. Lower behind head. Extend arms up.' },
    { id: 'skull-crusher', name: 'Skull Crusher', category: 'Push',
      muscle_group: 'Triceps', equipment: 'Barbell',
      instructions: 'Lie on bench. Hold bar above chest with arms extended. Lower bar to forehead. Press back up.' },
    { id: 'close-grip-bench', name: 'Close Grip Bench Press', category: 'Push',
      muscle_group: 'Triceps', equipment: 'Barbell',
      instructions: 'Grip bar shoulder width. Lower to chest. Press up. Emphasis on triceps over chest.' },
    { id: 'dip', name: 'Tricep Dip', category: 'Push',
      muscle_group: 'Triceps', equipment: 'Bodyweight',
      instructions: 'Stay upright on dip bars. Lower until 90 degree elbow angle. Press back up.' },
    { id: 'tricep-kickback', name: 'Tricep Kickback', category: 'Push',
      muscle_group: 'Triceps', equipment: 'Dumbbell',
      instructions: 'Hinge forward. Upper arm parallel to floor. Extend forearm back. Squeeze at top.' },
    { id: 'diamond-push-up', name: 'Diamond Push Up', category: 'Push',
      muscle_group: 'Triceps', equipment: 'Bodyweight',
      instructions: 'Form diamond shape with hands under chest. Lower and press. Heavy tricep emphasis.' },

    // ─── BACK (Pull) ─────────────────────────────────────────────
    { id: 'deadlift', name: 'Deadlift', category: 'Full Body',
      muscle_group: 'Back', equipment: 'Barbell',
      instructions: 'Bar over mid-foot. Hip-width stance. Hinge at hips, keep back flat. Drive through floor to stand.' },
    { id: 'barbell-row', name: 'Barbell Row', category: 'Pull',
      muscle_group: 'Back', equipment: 'Barbell',
      instructions: 'Hinge forward to 45 degrees. Pull bar to lower chest. Squeeze shoulder blades together.' },
    { id: 'pendlay-row', name: 'Pendlay Row', category: 'Pull',
      muscle_group: 'Back', equipment: 'Barbell',
      instructions: 'Torso parallel to floor. Pull bar explosively to chest from dead stop each rep.' },
    { id: 'db-row', name: 'Dumbbell Row', category: 'Pull',
      muscle_group: 'Back', equipment: 'Dumbbell',
      instructions: 'Plant one knee and hand on bench. Pull dumbbell to hip. Keep torso stable.' },
    { id: 'lat-pulldown', name: 'Lat Pulldown', category: 'Pull',
      muscle_group: 'Back', equipment: 'Cable',
      instructions: 'Wide overhand grip. Pull bar to upper chest. Lean back slightly. Squeeze lats at bottom.' },
    { id: 'close-grip-pulldown', name: 'Close Grip Pulldown', category: 'Pull',
      muscle_group: 'Back', equipment: 'Cable',
      instructions: 'Neutral grip attachment. Pull to chest. Elbows drive down and back.' },
    { id: 'cable-row', name: 'Seated Cable Row', category: 'Pull',
      muscle_group: 'Back', equipment: 'Cable',
      instructions: 'Sit upright. Pull handle to abdomen. Squeeze shoulder blades. Control return.' },
    { id: 'pull-up', name: 'Pull Up', category: 'Pull',
      muscle_group: 'Back', equipment: 'Bodyweight',
      instructions: 'Overhand grip wider than shoulders. Pull chin over bar. Full hang at bottom.' },
    { id: 'chin-up', name: 'Chin Up', category: 'Pull',
      muscle_group: 'Back', equipment: 'Bodyweight',
      instructions: 'Underhand shoulder-width grip. Pull chin over bar. More bicep emphasis than pull up.' },
    { id: 'assisted-pull-up', name: 'Assisted Pull Up', category: 'Pull',
      muscle_group: 'Back', equipment: 'Machine',
      instructions: 'Use assisted pull up machine. Kneel on pad. Pull to chest. Reduce assistance as you get stronger.' },
    { id: 't-bar-row', name: 'T-Bar Row', category: 'Pull',
      muscle_group: 'Back', equipment: 'Barbell',
      instructions: 'Straddle bar. Hinge forward. Pull bar to chest using V-grip. Keep back flat.' },
    { id: 'chest-supported-row', name: 'Chest Supported Row', category: 'Pull',
      muscle_group: 'Back', equipment: 'Machine',
      instructions: 'Lie chest on incline bench. Pull handles back. Removes lower back from equation.' },
    { id: 'straight-arm-pulldown', name: 'Straight Arm Pulldown', category: 'Pull',
      muscle_group: 'Back', equipment: 'Cable',
      instructions: 'Stand at high cable. Arms straight. Pull bar down to thighs in arc. Isolates lats.' },
    { id: 'rack-pull', name: 'Rack Pull', category: 'Pull',
      muscle_group: 'Back', equipment: 'Barbell',
      instructions: 'Set bar at knee height in rack. Pull to standing. Shorter range than deadlift. Load heavy.' },

    // ─── BICEPS (Pull) ───────────────────────────────────────────
    { id: 'barbell-curl', name: 'Barbell Curl', category: 'Pull',
      muscle_group: 'Biceps', equipment: 'Barbell',
      instructions: 'Stand with bar at hips. Curl to shoulder height. Keep elbows pinned to sides.' },
    { id: 'ez-bar-curl', name: 'EZ Bar Curl', category: 'Pull',
      muscle_group: 'Biceps', equipment: 'Barbell',
      instructions: 'Use angled EZ bar. Easier on wrists than straight bar. Curl to chin.' },
    { id: 'db-curl', name: 'Dumbbell Curl', category: 'Pull',
      muscle_group: 'Biceps', equipment: 'Dumbbell',
      instructions: 'Alternate or simultaneous. Supinate wrist at top for peak contraction.' },
    { id: 'hammer-curl', name: 'Hammer Curl', category: 'Pull',
      muscle_group: 'Biceps', equipment: 'Dumbbell',
      instructions: 'Neutral grip (thumbs up). Curl up. Targets brachialis and brachioradialis.' },
    { id: 'incline-db-curl', name: 'Incline Dumbbell Curl', category: 'Pull',
      muscle_group: 'Biceps', equipment: 'Dumbbell',
      instructions: 'Lie back on incline bench. Arms hang. Curl up. Greater stretch at bottom.' },
    { id: 'concentration-curl', name: 'Concentration Curl', category: 'Pull',
      muscle_group: 'Biceps', equipment: 'Dumbbell',
      instructions: 'Sit, brace elbow on inner thigh. Curl dumbbell up. Isolates bicep peak.' },
    { id: 'cable-curl', name: 'Cable Curl', category: 'Pull',
      muscle_group: 'Biceps', equipment: 'Cable',
      instructions: 'Low cable with bar. Constant tension throughout curl. Great for pump.' },
    { id: 'preacher-curl', name: 'Preacher Curl', category: 'Pull',
      muscle_group: 'Biceps', equipment: 'Machine',
      instructions: 'Brace upper arm on pad. Curl up. Eliminates cheating. Targets lower bicep.' },

    // ─── QUADS / LEGS ────────────────────────────────────────────
    { id: 'squat', name: 'Barbell Back Squat', category: 'Legs',
      muscle_group: 'Quads', equipment: 'Barbell',
      instructions: 'Bar on traps. Hip-width stance. Break at hips and knees simultaneously. Descend until thighs parallel. Drive up.' },
    { id: 'front-squat', name: 'Front Squat', category: 'Legs',
      muscle_group: 'Quads', equipment: 'Barbell',
      instructions: 'Bar on front delts. More upright torso than back squat. Greater quad emphasis.' },
    { id: 'goblet-squat', name: 'Goblet Squat', category: 'Legs',
      muscle_group: 'Quads', equipment: 'Dumbbell',
      instructions: 'Hold dumbbell at chest. Squat deep. Elbows inside knees at bottom. Great for form.' },
    { id: 'leg-press', name: 'Leg Press', category: 'Legs',
      muscle_group: 'Quads', equipment: 'Machine',
      instructions: 'Feet shoulder-width on platform. Lower sled until 90 degrees. Press through heels.' },
    { id: 'hack-squat', name: 'Hack Squat', category: 'Legs',
      muscle_group: 'Quads', equipment: 'Machine',
      instructions: 'Shoulders under pads. Feet low on platform for more quad. Descend deep, press up.' },
    { id: 'leg-extension', name: 'Leg Extension', category: 'Legs',
      muscle_group: 'Quads', equipment: 'Machine',
      instructions: 'Sit at machine. Extend legs fully. Squeeze quads at top. Control descent.' },
    { id: 'lunge', name: 'Lunge', category: 'Legs',
      muscle_group: 'Quads', equipment: 'Bodyweight',
      instructions: 'Step forward. Lower back knee toward floor. Push back to start. Alternate legs.' },
    { id: 'walking-lunge', name: 'Walking Lunge', category: 'Legs',
      muscle_group: 'Quads', equipment: 'Dumbbell',
      instructions: 'Lunge forward continuously. Hold dumbbells at sides. Keep torso upright.' },
    { id: 'bulgarian-split-squat', name: 'Bulgarian Split Squat', category: 'Legs',
      muscle_group: 'Quads', equipment: 'Dumbbell',
      instructions: 'Rear foot elevated on bench. Lower front leg to 90 degrees. Hardest leg exercise.' },
    { id: 'step-up', name: 'Step Up', category: 'Legs',
      muscle_group: 'Quads', equipment: 'Dumbbell',
      instructions: 'Step onto box with one foot. Drive up. Step down. Alternate. Hold dumbbells.' },

    // ─── HAMSTRINGS / GLUTES ─────────────────────────────────────
    { id: 'romanian-dl', name: 'Romanian Deadlift', category: 'Legs',
      muscle_group: 'Hamstrings', equipment: 'Barbell',
      instructions: 'Slight knee bend. Hinge at hips, push them back. Lower bar along legs. Feel hamstring stretch. Drive hips forward to stand.' },
    { id: 'stiff-leg-dl', name: 'Stiff Leg Deadlift', category: 'Legs',
      muscle_group: 'Hamstrings', equipment: 'Barbell',
      instructions: 'Legs nearly straight. Hinge deep. More range than RDL. Feel deep hamstring stretch.' },
    { id: 'leg-curl', name: 'Lying Leg Curl', category: 'Legs',
      muscle_group: 'Hamstrings', equipment: 'Machine',
      instructions: 'Lie face down. Curl heels to glutes. Squeeze at top. Control descent.' },
    { id: 'seated-leg-curl', name: 'Seated Leg Curl', category: 'Legs',
      muscle_group: 'Hamstrings', equipment: 'Machine',
      instructions: 'Sit upright. Curl legs down. Seated position creates more stretch at top.' },
    { id: 'nordic-curl', name: 'Nordic Curl', category: 'Legs',
      muscle_group: 'Hamstrings', equipment: 'Bodyweight',
      instructions: 'Kneel with feet anchored. Lower body forward slowly. Use hands to push back up.' },
    { id: 'hip-thrust', name: 'Hip Thrust', category: 'Legs',
      muscle_group: 'Glutes', equipment: 'Barbell',
      instructions: 'Upper back on bench. Bar across hips. Drive hips up. Squeeze glutes hard at top.' },
    { id: 'glute-bridge', name: 'Glute Bridge', category: 'Legs',
      muscle_group: 'Glutes', equipment: 'Bodyweight',
      instructions: 'Lie on floor. Feet flat. Drive hips up. Squeeze glutes. Easier than hip thrust.' },
    { id: 'cable-kickback', name: 'Cable Kickback', category: 'Legs',
      muscle_group: 'Glutes', equipment: 'Cable',
      instructions: 'Ankle strap on low cable. Kick leg back. Squeeze glute at extension.' },
    { id: 'sumo-deadlift', name: 'Sumo Deadlift', category: 'Legs',
      muscle_group: 'Glutes', equipment: 'Barbell',
      instructions: 'Wide stance, toes out. Grip inside legs. Drives hips through. More glute and inner thigh.' },

    // ─── CALVES ──────────────────────────────────────────────────
    { id: 'standing-calf-raise', name: 'Standing Calf Raise', category: 'Legs',
      muscle_group: 'Calves', equipment: 'Machine',
      instructions: 'Shoulders under pads. Rise on toes fully. Lower heel below platform for stretch.' },
    { id: 'seated-calf-raise', name: 'Seated Calf Raise', category: 'Legs',
      muscle_group: 'Calves', equipment: 'Machine',
      instructions: 'Pads on lower quads. Rise on toes. Targets soleus more than standing variation.' },
    { id: 'donkey-calf-raise', name: 'Donkey Calf Raise', category: 'Legs',
      muscle_group: 'Calves', equipment: 'Machine',
      instructions: 'Hinge at hips. Weight on lower back. Best stretch for gastroc.' },
    { id: 'single-leg-calf-raise', name: 'Single Leg Calf Raise', category: 'Legs',
      muscle_group: 'Calves', equipment: 'Bodyweight',
      instructions: 'Stand on one foot on edge of step. Full range of motion. Hold weight if too easy.' },

    // ─── CORE ─────────────────────────────────────────────────────
    { id: 'plank', name: 'Plank', category: 'Full Body',
      muscle_group: 'Core', equipment: 'Bodyweight',
      instructions: 'Forearms on floor. Body straight from head to heel. Squeeze everything. Hold.' },
    { id: 'ab-wheel', name: 'Ab Wheel Rollout', category: 'Full Body',
      muscle_group: 'Core', equipment: 'Bodyweight',
      instructions: 'Kneel with wheel. Roll forward until near-horizontal. Pull back using core.' },
    { id: 'cable-crunch', name: 'Cable Crunch', category: 'Full Body',
      muscle_group: 'Core', equipment: 'Cable',
      instructions: 'Kneel at high cable with rope. Pull elbows to knees. Crunch, not pull with arms.' },
    { id: 'hanging-leg-raise', name: 'Hanging Leg Raise', category: 'Full Body',
      muscle_group: 'Core', equipment: 'Bodyweight',
      instructions: 'Hang from bar. Raise legs to 90 degrees or higher. Avoid swinging.' },
    { id: 'russian-twist', name: 'Russian Twist', category: 'Full Body',
      muscle_group: 'Core', equipment: 'Bodyweight',
      instructions: 'Sit at 45 degrees. Feet off floor. Rotate torso side to side. Hold weight for difficulty.' },
    { id: 'dead-bug', name: 'Dead Bug', category: 'Full Body',
      muscle_group: 'Core', equipment: 'Bodyweight',
      instructions: 'Lie on back. Arms and legs up. Lower opposite arm/leg simultaneously. Keep lower back flat.' },
    { id: 'side-plank', name: 'Side Plank', category: 'Full Body',
      muscle_group: 'Core', equipment: 'Bodyweight',
      instructions: 'Side-lying on forearm. Hips up. Body straight. Hold. Targets obliques.' },
    { id: 'v-up', name: 'V-Up', category: 'Full Body',
      muscle_group: 'Core', equipment: 'Bodyweight',
      instructions: 'Lie flat. Simultaneously raise legs and torso. Touch hands to feet at top.' },

    // ─── CARDIO ──────────────────────────────────────────────────
    { id: 'treadmill-run', name: 'Treadmill Run', category: 'Full Body',
      muscle_group: 'Cardio', equipment: 'Machine',
      instructions: 'Set speed and incline. Maintain steady pace. For HIIT, alternate sprint and walk.' },
    { id: 'rowing-machine', name: 'Rowing Machine', category: 'Full Body',
      muscle_group: 'Cardio', equipment: 'Machine',
      instructions: 'Drive with legs first, then lean back, then pull. Reverse on return. Full body cardio.' },
    { id: 'stationary-bike', name: 'Stationary Bike', category: 'Full Body',
      muscle_group: 'Cardio', equipment: 'Machine',
      instructions: 'Set seat height so knee slightly bent at bottom. Low impact cardio.' },
    { id: 'jump-rope', name: 'Jump Rope', category: 'Full Body',
      muscle_group: 'Cardio', equipment: 'Bodyweight',
      instructions: 'Land on balls of feet. Keep jumps small and efficient. Great for conditioning.' },
    { id: 'burpee', name: 'Burpee', category: 'Full Body',
      muscle_group: 'Cardio', equipment: 'Bodyweight',
      instructions: 'Squat, kick feet back to push-up position, push up, jump feet forward, jump up. Brutal conditioning.' },
    { id: 'battle-ropes', name: 'Battle Ropes', category: 'Full Body',
      muscle_group: 'Cardio', equipment: 'Machine',
      instructions: 'Alternate arm waves or simultaneous slams. Keep continuous motion.' },
  ];

  exercises.forEach((ex) => {
    db.runSync(
      `INSERT OR IGNORE INTO exercises 
       (id, name, category, muscle_group, equipment, instructions, is_custom)
       VALUES (?, ?, ?, ?, ?, ?, 0)`,
      [ex.id, ex.name, ex.category, ex.muscle_group, ex.equipment, ex.instructions]
    );
  });
};
